import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FileDown, Activity, BarChart3, Brain, AlertTriangle } from 'lucide-react';
import jsPDF from 'jspdf';
import Layout from '@/components/Layout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { getEntries, getPredictions, getProfile } from '@/lib/storage';
import { HEADACHE_TYPE_LABELS, TRIGGER_LABELS, type HeadacheEntry, type PredictionResult, type Trigger } from '@/types/headache';

export default function DoctorReport() {
  const navigate = useNavigate();
  const [entries, setEntries] = useState<HeadacheEntry[]>([]);
  const [predictions, setPredictions] = useState<PredictionResult[]>([]);

  useEffect(() => {
    if (!localStorage.getItem('neurotrack_auth')) { navigate('/auth?mode=login'); return; }
    setEntries(getEntries());
    setPredictions(getPredictions());
  }, [navigate]);

  const profile = getProfile();
  const avgSeverity = entries.length > 0 ? (entries.reduce((s, e) => s + e.intensity, 0) / entries.length).toFixed(1) : '0';

  // Most common type
  const typeCounts: Record<string, number> = {};
  predictions.forEach(p => { typeCounts[p.predicted_type] = (typeCounts[p.predicted_type] || 0) + 1; });
  const commonType = Object.entries(typeCounts).sort((a, b) => b[1] - a[1])[0];

  // Top triggers
  const trigCounts: Record<string, number> = {};
  entries.forEach(e => e.triggers.forEach(t => { trigCounts[t] = (trigCounts[t] || 0) + 1; }));
  const topTriggers = Object.entries(trigCounts).sort((a, b) => b[1] - a[1]).slice(0, 4);

  // Severity distribution
  const sevDist = { mild: 0, moderate: 0, severe: 0 };
  entries.forEach(e => {
    if (e.intensity <= 3) sevDist.mild++;
    else if (e.intensity <= 6) sevDist.moderate++;
    else sevDist.severe++;
  });

  const downloadPDF = () => {
    const doc = new jsPDF();
    let y = 20;

    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('NeuroTrack AI - Patient Report', 20, y); y += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, y); y += 6;
    doc.text(`Patient: ${profile.name}`, 20, y); y += 10;

    doc.setDrawColor(200);
    doc.line(20, y, 190, y); y += 10;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 20, y); y += 8;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Headache Episodes: ${entries.length}`, 20, y); y += 6;
    doc.text(`Average Severity: ${avgSeverity}/10`, 20, y); y += 6;
    doc.text(`Most Common Type: ${commonType ? HEADACHE_TYPE_LABELS[commonType[0] as keyof typeof HEADACHE_TYPE_LABELS] : 'N/A'}`, 20, y); y += 6;
    doc.text(`Tracking Period: ${entries.length > 0 ? `${entries[entries.length - 1].date} to ${entries[0].date}` : 'N/A'}`, 20, y); y += 12;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Severity Distribution', 20, y); y += 8;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Mild (1-3): ${sevDist.mild} episodes`, 20, y); y += 6;
    doc.text(`Moderate (4-6): ${sevDist.moderate} episodes`, 20, y); y += 6;
    doc.text(`Severe (7-10): ${sevDist.severe} episodes`, 20, y); y += 12;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Common Triggers', 20, y); y += 8;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    topTriggers.forEach(([t, c]) => {
      doc.text(`${TRIGGER_LABELS[t as Trigger] || t}: ${c} occurrence${c > 1 ? 's' : ''}`, 20, y); y += 6;
    });
    y += 6;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Recent Episodes', 20, y); y += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    entries.slice(0, 10).forEach(e => {
      const pred = predictions.find(p => p.entry_id === e.id);
      doc.text(`${e.date} | Intensity: ${e.intensity}/10 | ${e.duration_minutes}min | ${pred ? HEADACHE_TYPE_LABELS[pred.predicted_type] : 'Unclassified'}`, 20, y);
      y += 5;
      if (y > 270) { doc.addPage(); y = 20; }
    });

    y += 8;
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text('This report was generated by NeuroTrack AI for informational purposes only. Not a medical diagnosis.', 20, y);

    doc.save('NeuroTrack_Report.pdf');
  };

  return (
    <Layout>
      <div className="max-w-3xl mx-auto space-y-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h1 className="font-display text-2xl md:text-3xl font-bold">Doctor Report</h1>
            <p className="text-muted-foreground mt-1">Share this summary with your healthcare provider</p>
          </div>
          <Button onClick={downloadPDF} className="gradient-primary border-0" disabled={entries.length === 0}>
            <FileDown className="h-4 w-4 mr-2" /> Download PDF
          </Button>
        </div>

        {entries.length === 0 ? (
          <Card><CardContent className="p-8 text-center">
            <p className="text-muted-foreground">No data to generate a report. Start logging headaches first.</p>
          </CardContent></Card>
        ) : (
          <>
            {/* Overview */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {[
                { icon: Activity, label: 'Total Episodes', value: entries.length },
                { icon: BarChart3, label: 'Avg Severity', value: `${avgSeverity}/10` },
                { icon: Brain, label: 'Common Type', value: commonType ? HEADACHE_TYPE_LABELS[commonType[0] as keyof typeof HEADACHE_TYPE_LABELS].split(' ')[0] : '—' },
                { icon: AlertTriangle, label: 'Severe Count', value: sevDist.severe },
              ].map(s => (
                <Card key={s.label}>
                  <CardContent className="p-4 text-center">
                    <s.icon className="h-5 w-5 mx-auto text-primary mb-2" />
                    <p className="text-xl font-bold font-display">{s.value}</p>
                    <p className="text-xs text-muted-foreground">{s.label}</p>
                  </CardContent>
                </Card>
              ))}
            </div>

            {/* Severity Distribution */}
            <Card>
              <CardHeader className="pb-3"><CardTitle className="text-base">Severity Distribution</CardTitle></CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {[
                    { label: 'Mild (1-3)', count: sevDist.mild, color: 'bg-success' },
                    { label: 'Moderate (4-6)', count: sevDist.moderate, color: 'bg-warning' },
                    { label: 'Severe (7-10)', count: sevDist.severe, color: 'bg-destructive' },
                  ].map(s => (
                    <div key={s.label}>
                      <div className="flex justify-between text-sm mb-1">
                        <span>{s.label}</span>
                        <span className="font-medium">{s.count}</span>
                      </div>
                      <div className="h-2 rounded-full bg-secondary">
                        <div className={`h-full rounded-full ${s.color}`} style={{ width: `${entries.length > 0 ? (s.count / entries.length) * 100 : 0}%` }} />
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Top Triggers */}
            <Card>
              <CardHeader className="pb-3"><CardTitle className="text-base">Common Triggers</CardTitle></CardHeader>
              <CardContent>
                {topTriggers.length > 0 ? (
                  <div className="flex flex-wrap gap-2">
                    {topTriggers.map(([t, c]) => (
                      <span key={t} className="px-3 py-1.5 rounded-full text-sm bg-accent/10 text-accent border border-accent/20">
                        {TRIGGER_LABELS[t as Trigger] || t} ({c})
                      </span>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground">No triggers recorded yet.</p>
                )}
              </CardContent>
            </Card>

            {/* Timeline */}
            <Card>
              <CardHeader className="pb-3"><CardTitle className="text-base">Recent Timeline</CardTitle></CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {entries.slice(0, 8).map(e => {
                    const pred = predictions.find(p => p.entry_id === e.id);
                    return (
                      <div key={e.id} className="flex items-center gap-3 text-sm">
                        <div className={`w-3 h-3 rounded-full shrink-0 ${
                          e.intensity >= 7 ? 'bg-destructive' : e.intensity >= 4 ? 'bg-warning' : 'bg-success'
                        }`} />
                        <span className="text-muted-foreground w-24 shrink-0">{e.date}</span>
                        <span className="font-medium">{e.intensity}/10</span>
                        <span className="text-muted-foreground">·</span>
                        <span>{pred ? HEADACHE_TYPE_LABELS[pred.predicted_type] : 'Unclassified'}</span>
                      </div>
                    );
                  })}
                </div>
              </CardContent>
            </Card>

            <p className="text-xs text-muted-foreground text-center">
              This report is generated for informational purposes only. It is not a medical diagnosis. Please consult a healthcare professional.
            </p>
          </>
        )}
      </div>
    </Layout>
  );
}
